//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AonWeb.FluentHttp {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AonWeb.FluentHttp.SR", typeof(SR).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method must not be null or empty..
        /// </summary>
        internal static string ArgumentMethodNullOrEmptyError {
            get {
                return ResourceManager.GetString("ArgumentMethodNullOrEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path must be absolute and begin with a &quot;/&quot;..
        /// </summary>
        internal static string ArgumentPathMustBeAbsoluteError {
            get {
                return ResourceManager.GetString("ArgumentPathMustBeAbsoluteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri must be absolute..
        /// </summary>
        internal static string ArgumentUriMustBeAbsoluteError {
            get {
                return ResourceManager.GetString("ArgumentUriMustBeAbsoluteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri must not be null or empty..
        /// </summary>
        internal static string ArgumentUriNullOrEmptyError {
            get {
                return ResourceManager.GetString("ArgumentUriNullOrEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current Cache Context must have Request Message..
        /// </summary>
        internal static string CacheContextRequestMessageRequiredError {
            get {
                return ResourceManager.GetString("CacheContextRequestMessageRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current Cache Context must have ResponseInfo..
        /// </summary>
        internal static string CacheContextResponseInfoRequiredError {
            get {
                return ResourceManager.GetString("CacheContextResponseInfoRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not construct context of type {0}. Could not find constructor with {1} parameter(s). {2}.
        /// </summary>
        internal static string ConstructorMissingErrorFormat {
            get {
                return ResourceManager.GetString("ConstructorMissingErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This handler has already been registered..
        /// </summary>
        internal static string HanderAlreadyExistsError {
            get {
                return ResourceManager.GetString("HanderAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A handler of type &apos;{0}&apos; has not been registered..
        /// </summary>
        internal static string HanderDoesNotExistErrorFormat {
            get {
                return ResourceManager.GetString("HanderDoesNotExistErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum allowed number redirects ({0}) was reached. {1}.
        /// </summary>
        internal static string MaxAutoRedirectsErrorFormat {
            get {
                return ResourceManager.GetString("MaxAutoRedirectsErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MediaTypeFormatter is available to read an object of type &apos;{0}&apos; from content with media type &apos;{1}&apos;. {2}.
        /// </summary>
        internal static string NoReadFormatterForMimeTypeErrorFormat {
            get {
                return ResourceManager.GetString("NoReadFormatterForMimeTypeErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MediaTypeFormatter is available to writean object of type &apos;{0}&apos; to content with media type {1}. {2}.
        /// </summary>
        internal static string NoWriteFormatterForMimeTypeErrorFormat {
            get {
                return ResourceManager.GetString("NoWriteFormatterForMimeTypeErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected type &apos;{0}&apos;, actual type {1}. {2}.
        /// </summary>
        internal static string TypeMismatchErrorFormat {
            get {
                return ResourceManager.GetString("TypeMismatchErrorFormat", resourceCulture);
            }
        }
    }
}
