call AonWeb.FluentHttp\_CreateNewNuGetPackage\RunMeToUploadNuGetPackage.cmd
call AonWeb.FluentHttp.Hal\_CreateNewNuGetPackage\RunMeToUploadNuGetPackage.cmd
call AonWeb.FluentHttp.Mocks\_CreateNewNuGetPackage\RunMeToUploadNuGetPackage.cmd
REM call AonWeb.FluentHttp.Autofac\_CreateNewNuGetPackage\RunMeToUploadNuGetPackage.cmd