@ECHO OFF
SET THIS_SCRIPTS_DIRECTORY=%~dp0

PowerShell -NoProfile -ExecutionPolicy Bypass -Command "%THIS_SCRIPTS_DIRECTORY%tools\_CreateNewNuGetPackage\DoNotModify\UploadNuGetPackage.ps1 -ProjectPath \"%THIS_SCRIPTS_DIRECTORY%AonWeb.FluentHttp.Serialization\bin\Release\" -NoPromptForPushPackageToNuGetGallery -PushPackageToNuGetGallery"
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "%THIS_SCRIPTS_DIRECTORY%tools\_CreateNewNuGetPackage\DoNotModify\UploadNuGetPackage.ps1 -ProjectPath \"%THIS_SCRIPTS_DIRECTORY%AonWeb.FluentHttp\bin\Release\" -NoPromptForPushPackageToNuGetGallery -PushPackageToNuGetGallery"
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "%THIS_SCRIPTS_DIRECTORY%tools\_CreateNewNuGetPackage\DoNotModify\UploadNuGetPackage.ps1 -ProjectPath \"%THIS_SCRIPTS_DIRECTORY%AonWeb.FluentHttp.HAL.Serialization\bin\Release\" -NoPromptForPushPackageToNuGetGallery -PushPackageToNuGetGallery"
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "%THIS_SCRIPTS_DIRECTORY%tools\_CreateNewNuGetPackage\DoNotModify\UploadNuGetPackage.ps1 -ProjectPath \"%THIS_SCRIPTS_DIRECTORY%AonWeb.FluentHttp.Hal\bin\Release\" -NoPromptForPushPackageToNuGetGallery -PushPackageToNuGetGallery"
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "%THIS_SCRIPTS_DIRECTORY%tools\_CreateNewNuGetPackage\DoNotModify\UploadNuGetPackage.ps1 -ProjectPath \"%THIS_SCRIPTS_DIRECTORY%AonWeb.FluentHttp.Mocks\bin\Release\" -NoPromptForPushPackageToNuGetGallery -PushPackageToNuGetGallery"
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "%THIS_SCRIPTS_DIRECTORY%tools\_CreateNewNuGetPackage\DoNotModify\UploadNuGetPackage.ps1 -ProjectPath \"%THIS_SCRIPTS_DIRECTORY%AonWeb.FluentHttp.Autofac\bin\Release\" -NoPromptForPushPackageToNuGetGallery -PushPackageToNuGetGallery"
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "%THIS_SCRIPTS_DIRECTORY%tools\_CreateNewNuGetPackage\DoNotModify\UploadNuGetPackage.ps1 -ProjectPath \"%THIS_SCRIPTS_DIRECTORY%AonWeb.FluentHttp.Full\bin\Release\" -NoPromptForPushPackageToNuGetGallery -PushPackageToNuGetGallery"
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "%THIS_SCRIPTS_DIRECTORY%tools\_CreateNewNuGetPackage\DoNotModify\UploadNuGetPackage.ps1 -ProjectPath \"%THIS_SCRIPTS_DIRECTORY%AonWeb.FluentHttp.GraphQL\bin\Release\" -NoPromptForPushPackageToNuGetGallery -PushPackageToNuGetGallery"
REM PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& \"%THIS_SCRIPTS_DIRECTORY%tools\_CreateNewNuGetPackage\DoNotModify\UploadNuGetPackage.ps1\"  -ProjectPath \"%THIS_SCRIPTS_DIRECTORY%AonWeb.FluentHttp.Xamarin\bin\Release\" -NoPromptForPushPackageToNuGetGallery -PushPackageToNuGetGallery"

pause